# Generated by Django 4.2 on 2023-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_raport_analizraport_blogs_description_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='location',
            field=models.CharField(max_length=2000),
        ),
    ]
