# Generated by Django 4.2 on 2023-07-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_setting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='location',
            field=models.URLField(max_length=2000),
        ),
    ]
